### ISSUE TITLE
Jeg mangler push adgang

### ISSUE THREAD

**Issue by nordfalk** [petertbdtu/gr09.8-Simulator-til-kirurgisk-traening#1]

**Comment by nordfalk** [comment]
```
public class WifiP2P {

    private WifiManager WM;
    private WifiP2pManager WPM;
    private WifiP2pManager.Channel WPMC;
    private BroadcastReceiver BR;
    private IntentFilter IF;
    private WifiP2pManager.PeerListListener PLL;
    private WifiP2pManager.ConnectionInfoListener CIL;

    private InetAddress broadcastAddress;
    private String myMacAddress;
    private boolean isGroupOwner;
    private Context context;

    public WifiP2P(Context context, boolean isGroupOwner){
        this.context = context;
        this.isGroupOwner = isGroupOwner;
        checkWifi();
        init();
    }

    private void init(){
        WPM = (WifiP2pManager) context.getSystemService(context.WIFI_P2P_SERVICE);
        /* UDESTÅR - Herunder kommer fejl hvis getSystemService(context.WIFI_P2P_SERVICE) returnerer null
     java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.wifi.p2p.WifiP2pManager$Channel android.net.wifi.p2p.WifiP2pManager.initialize(android.content.Context, android.os.Looper, android.net.wifi.p2p.WifiP2pManager$ChannelListener)' on a null object reference
        at gruppe98.dtu.dk.gr098_simulatortilkirurgisktraening.objects.WifiP2P.init(WifiP2P.java:46)
        at gruppe98.dtu.dk.gr098_simulatortilkirurgisktraening.objects.WifiP2P.<init>(WifiP2P.java:41)
        at gruppe98.dtu.dk.gr098_simulatortilkirurgisktraening.activities.InsufflatorVisningActivity.onRequestPermissionsResult(InsufflatorVisningActivity.java:78)
         */
        WPMC = WPM.initialize(context,context.getMainLooper(),null);

```
